version: '2.1'
services:


  backend:
    image: energy-platform-backend
    ports:
      - "8082:8082"
    depends_on:
       db:
          condition: service_healthy

    container_name: backend_container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/energy-utility-platform-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 20s
      retries: 5
    ports:
      - "5432:5432"
    container_name: database
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=energy-utility-platform-db
      - POSTGRES_HOST_AUTH_METHOD=trust

  envoy-proxy:
    image: envoy-image
    ports:
      - "9091:9091"
      - "8080:8080"
    depends_on:
      - backend
    container_name: envoy-image
      
  energy_platform_app:
    image:  energy-platform-frontend
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    container_name: frontend_container
    
    
  grpc-server-container:
    image: grpc-server
    container_name: grpc-server-container
    ports:
      - "9090:9090"